---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harvis-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-manifest/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: harvis-source
  # validation: client  # Deprecated field
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: harvis-prod
      namespace: ai-agents
  timeout: 5m0s
